import { Container } from "@/components/ui/Container";
import { cn } from "@/lib/utils/cn";

const pillars = [
  ["01", "Entity Clarity", "Make it clear who the business is, what it does, and who it serves."],
  ["02", "Content Depth", "Create genuinely useful information around important topics."],
  ["03", "Source Quality", "Build credible, trustworthy sources that provide meaningful context."],
  ["04", "Structured Information", "Use structured data and consistent information architecture to aid interpretation."],
  ["05", "Authority", "Develop meaningful digital authority and references over time."],
  ["06", "Measurement", "Monitor representation across relevant AI-assisted and search experiences."],
] as const;

const surfaces = ["Website", "Business profile", "Articles", "Directories", "Press", "Industry references"];

export function GeoSections() {
  return <>
    <section className="border-b border-border py-20 md:py-32"><Container size="wide"><div className="grid gap-10 lg:grid-cols-12"><div className="lg:col-span-5"><Eyebrow>What is GEO?</Eyebrow><h2 className="mt-6 text-display-lg font-bold tracking-tighter text-foreground">Generative Engine Optimization is about being understood.</h2></div><div className="space-y-5 text-base leading-relaxed text-foreground-muted lg:col-span-5 lg:col-start-8"><p>Traditional SEO focuses heavily on helping pages become discoverable and competitive within search engines.</p><p>GEO considers how brands and information are represented within newer AI-assisted and generative discovery experiences.</p><p className="border-l border-accent pl-5 text-foreground">SEO remains foundational. GEO extends the conversation into emerging AI discovery.</p></div></div></Container></section>
    <section className="border-b border-border py-20 md:py-32"><Container size="wide"><Eyebrow>Two connected disciplines</Eyebrow><h2 className="mt-6 max-w-3xl text-display-lg font-bold tracking-tighter text-foreground">Different emphasis. Shared foundation.</h2><div className="mt-12 grid gap-px border border-border bg-border md:grid-cols-2"><Compare title="SEO" items={["Search rankings", "Keywords", "Crawling", "Indexation", "Content", "Links", "Search results"]} /><Compare title="GEO" items={["Information retrieval", "Context", "Entity understanding", "Source quality", "Structured information", "Brand authority", "AI-assisted answers"]} /></div></Container></section>
    <section className="border-b border-border py-20 md:py-32"><Container size="wide"><div className="grid gap-12 lg:grid-cols-12"><div className="lg:col-span-4"><Eyebrow>How discovery works</Eyebrow><h2 className="mt-6 text-display-lg font-bold tracking-tighter text-foreground">Context travels before the answer.</h2></div><div className="lg:col-span-7 lg:col-start-6"><div className="space-y-0">{["User question", "Retrieval", "Sources", "Context", "Model / search system", "Generated response", "User decision"].map((step, index) => <div key={step} className="flex items-center gap-5 border-b border-border py-4"><span className="text-xs font-mono text-accent">0{index + 1}</span><span className={cn("text-lg", index === 6 ? "text-foreground" : "text-foreground-muted")}>{step}</span></div>)}</div><p className="mt-7 text-sm leading-relaxed text-foreground-subtle">Businesses can improve the quality of their digital presence through source quality, clarity, entity consistency, structured information, authority, and relevance. They cannot control the model or guarantee an answer.</p></div></div></Container></section>
    <section className="border-b border-border py-20 md:py-32"><Container size="wide"><Eyebrow>GEO pillars</Eyebrow><div className="mt-10 grid gap-px border border-border bg-border sm:grid-cols-2 lg:grid-cols-3">{pillars.map(([number, title, text]) => <div key={number} className="bg-background p-7"><span className="text-xs font-mono text-accent">{number}</span><h3 className="mt-8 text-heading-md font-semibold text-foreground">{title}</h3><p className="mt-3 text-sm leading-relaxed text-foreground-muted">{text}</p></div>)}</div></Container></section>
    <section className="border-b border-border py-20 md:py-32"><Container size="wide"><div className="grid gap-12 lg:grid-cols-12"><div className="lg:col-span-5"><Eyebrow>Entity clarity</Eyebrow><h2 className="mt-6 text-display-lg font-bold tracking-tighter text-foreground">One brand. Consistent signals.</h2><p className="mt-6 max-w-md text-base leading-relaxed text-foreground-muted">AI systems need context. Consistent information across a digital ecosystem helps reduce ambiguity about a brand, its services, locations, people, and expertise.</p></div><div className="lg:col-span-6 lg:col-start-7"><div className="border border-border p-6 md:p-8"><div className="mx-auto flex max-w-xs items-center justify-center border border-accent bg-accent/10 px-5 py-4 text-center text-sm font-semibold text-foreground">Brand</div><div className="mx-auto h-8 w-px bg-accent" aria-hidden="true" /><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{surfaces.map((surface) => <div key={surface} className="border border-border bg-background-elevated px-3 py-4 text-center text-xs text-foreground-muted">{surface}</div>)}</div><div className="mx-auto mt-4 h-8 w-px bg-border" aria-hidden="true" /><p className="text-center text-xs font-mono uppercase tracking-widest text-accent">Consistent entity context</p></div></div></div></Container></section>
    <section className="border-b border-border py-20 md:py-32"><Container size="wide"><div className="grid gap-10 lg:grid-cols-12"><div className="lg:col-span-5"><Eyebrow>Content for discovery</Eyebrow><h2 className="mt-6 text-display-lg font-bold tracking-tighter text-foreground">Create content worth retrieving.</h2></div><div className="grid gap-5 sm:grid-cols-2 lg:col-span-6 lg:col-start-7">{["Answer specific questions", "Provide useful context", "Demonstrate expertise", "Use clear structure", "Reference credible information", "Avoid meaningless repetition"].map((item) => <div key={item} className="border-l border-border pl-4 text-sm leading-relaxed text-foreground-muted">{item}</div>)}</div></div></Container></section>
    <section className="border-b border-border py-20 md:py-32"><Container size="wide"><div className="grid gap-10 lg:grid-cols-12"><div className="lg:col-span-5"><Eyebrow>Technical foundation</Eyebrow><h2 className="mt-6 text-display-lg font-bold tracking-tighter text-foreground">Structured information helps machines interpret meaning.</h2></div><div className="lg:col-span-6 lg:col-start-7"><div className="flex flex-wrap gap-2">{["Organization", "WebSite", "Service", "Article", "BreadcrumbList", "FAQ where appropriate"].map((item) => <span key={item} className="border border-border bg-background-elevated px-3 py-2 text-xs font-mono text-foreground-muted">{item}</span>)}</div><p className="mt-6 text-sm leading-relaxed text-foreground-subtle">Structured data is a signal for interpretation, not a guarantee of inclusion in AI-generated answers.</p></div></div></Container></section>
    <section className="py-20 md:py-32"><Container size="wide"><Eyebrow>Emerging process</Eyebrow><h2 className="mt-6 max-w-3xl text-display-lg font-bold tracking-tighter text-foreground">A disciplined way to prepare for change.</h2><div className="mt-12 grid gap-0 border-y border-border md:grid-cols-4">{["Discover", "Clarify", "Structure", "Measure"].map((step, index) => <div key={step} className="border-b border-border p-6 last:border-b-0 md:border-b-0 md:border-r md:last:border-r-0"><span className="text-xs font-mono text-accent">0{index + 1}</span><h3 className="mt-8 text-heading-md font-semibold text-foreground">{step}</h3><p className="mt-3 text-sm leading-relaxed text-foreground-muted">Understand the current signals, identify ambiguity, improve the foundation, and observe what changes.</p></div>)}</div></Container></section>
  </>;
}

function Eyebrow({ children }: { children: React.ReactNode }) { return <div className="flex items-center gap-3"><span className="h-px w-6 bg-accent" /><span className="text-xs font-mono uppercase tracking-widest text-foreground-muted">{children}</span></div>; }
function Compare({ title, items }: { title: string; items: readonly string[] }) { return <div className="bg-background p-7 md:p-10"><h3 className="text-heading-xl font-bold text-foreground">{title}</h3><ul className="mt-8 space-y-4">{items.map((item) => <li key={item} className="border-b border-border pb-3 text-sm text-foreground-muted">{item}</li>)}</ul></div>; }