export const analyticsEvents = {
  pageView: "page_view",
  heroCtaClick: "hero_cta_click",
  serviceCtaClick: "service_cta_click",
  servicesMenuOpened: "services_menu_opened",
  serviceCategoryClick: "service_category_click",
  industryHubClick: "industry_hub_click",
  toolsHubClick: "tools_hub_click",
  aiSearchVisibilityClick: "ai_search_visibility_click",
  aeoClick: "aeo_click",
  geoClick: "geo_click",
  auditCtaClick: "audit_cta_click",
  toolStarted: "tool_started",
  caseStudyViewed: "case_study_viewed",
  insightViewed: "insight_viewed",
  workCtaClick: "work_cta_click",
  insightCtaClick: "insight_cta_click",
  contactCtaClick: "contact_cta_click",
  contactFormView: "contact_form_view",
  contactFormStart: "contact_form_start",
  contactFormFieldInteraction: "contact_form_field_interaction",
  contactFormSubmit: "contact_form_submit",
  contactFormSuccess: "contact_form_success",
  contactFormError: "contact_form_error",
  leadCreated: "lead_created",
  leadQualified: "lead_qualified",
  leadWon: "lead_won",
  leadFormView: "lead_form_view",
  leadFormStart: "lead_form_start",
} as const;

export type AnalyticsEvent = (typeof analyticsEvents)[keyof typeof analyticsEvents];